url: "https://alifalhasan.github.io"
baseurl: ""
title: "Alif Al Hasan"
# description: "Computer Science PhD Student @ CWRU"
author: "Alif Al Hasan"

logo: "/assets/img/alifalhasan.jpg"


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap